### ISSUE TITLE
Editor shows errors in examples folder even though they can deploy without problems

### ISSUE THREAD

**Issue by JWood48** [toitware/ide-tools#198] opened 2022-02-24 07:36 UTC
Steps to reproduce:

* Clone and open this driver: https://github.com/toitware/toit-tm1640
* Run toit pkg install in the root folder
* Run toit pkg install in the examples folder
* Open the project in vscode
* The tm1640.toit file is fine
* All toit files in examples are showing problems **some** imports:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1113096/155478556-52d64db1-b6cb-40bc-982b-f6c08b50350a.png">

Environment:
* Windows 11
* toit version: 1.19.0

**Comment by floitsch** [comment] 2022-02-24 18:34
This is a difficult problem to solve:
In this scenario there are two package.lock files that can be used to analyze a file: the one in the root of the package, and the one in the examples folder. The vscode extension uses the one that is at the root of the folder, which leads to the shown errors.

The work-around is to open the example folders in a fresh vscode window.

You could argue that the vscode extension should just find the "closest" `package.lock` file and use that one instead. However, this leads to other problems:
1. the installed packages are in a `.packages` folder and each package (often) has its own package.lock file. However, we never executed `toit pkg install` for the installed package itself. Opening a package file would thus lead to errors in the package files. We would need to special case `.packages` files.
2. without a deterministic/simple way of deciding which package.lock is used, you could end up with a file that has two different diagnostics. Imagine the following scenario

Imagine you are writing a package `morse` that uses the package `sound`.
In your `morse.toit` file you have the following line:
``` toit
  sound.emit_beep --ms=100
```

Now, let's imagine there are two versions of the `sound` package: v1.0.0 and v1.2.0.
However, version v1.2.0 has deprecated the `emit_beep` function, thus leading to a warning when the function is used.

In the package.lock file of the morse package you installed the `v1.0.0` version. Everything looks great.
Later you create the examples, and end up installing `v1.2.0` (maybe the version was just published). Suddenly the `morse.toit` file in your package should show a warning.

The problem is now, that this warning is outside the examples folder (it's in the src/morse.toit file), but is triggered by the choice of installed packages in your examples folder.

There aren't really any good solutions now:
- Don't show the warning. That's a bit weird, as running `toit.compile --analyze examples/...` would show the warning.
- Show the warning. Feels wrong, as the main package.lock uses a package that doesn't have this warning.
Use the latest analysis to decide whether to show the warning or not. This is what we had at some point, and the files kept turning warnings on and off.

Here I only used a warning, but you can imagine that errors are even worse. It's very annoying if the compiler claims that a program has an error, but the IDE doesn't see it.

Note, that goto-definition has similar issues: the target depends on the used package.lock file.

I'm open for suggestions on how this should be handled.

**Comment by kasperl** [comment] 2023-12-18 08:08
This has been fixed in SDK v2.0.0-alpha.126, which ships as part of Jaguar v1.24.0.

Thanks for the report!

**Closed by kasperl** 2023-12-18 08:08 UTC
